Use const since local variable is never mutated
Spotted while trying this project out with the latest Zig `master` (`0.12.0-dev.1676+40b8c993f`)

```
src/main.zig:169:9: error: local variable is never mutated
    var kwargs = Options(RangeOpt).parse(_kwargs);
        ^~~~~~
src/main.zig:169:9: note: consider using 'const'
src/main.zig:183:9: error: local variable is never mutated
    var data = [_]u8{ 0, 1, 2, 3, 4, 5 };
        ^~~~
src/main.zig:183:9: note: consider using 'const'
```